### PR TITLE
Fix import warning on PromptTemplate

### PR DESCRIPTION
**Pull request by dmyoung9**
This should silence the warning added in LangChain 0.0.302 😁

### CODE REVIEW

**Comment by Jped** [comment]
This is what I get from my local test 
Screenshot 2023-10-02 at 1 21 22 PM

**Comment by dmyoung9** [comment]
Ah, you know what... I've made an oversight. I will fix it today 👌

**Comment by dmyoung9** [comment]
@Jped Give it a try now. It just slipped my mind there was another import used there 😅

**Comment by Jped** [comment]
@dmyoung9 looks good -- mind changing the library version?

**Comment by dmyoung9** [comment]
Done!

**Review by Jped — APPROVED** [review]

**Comment by dmyoung9** [comment]
Thanks for the merge! Glad I could help ☺️

**Pull request merged**
